// Base de datos COMPLETA de dispositivos y configuraciones - TODOS LOS MODELOS EXISTENTES + EXPANSIÓN
const deviceDatabase = {
  APPLE: {
    "iPhone Classic": ["iPhone (2007)", "iPhone 3G", "iPhone 3GS"],
    "iPhone 4 Series": ["iPhone 4", "iPhone 4S"],
    "iPhone 5 Series": ["iPhone 5", "iPhone 5c", "iPhone 5s"],
    "iPhone SE Series": ["iPhone SE (1st gen)", "iPhone SE (2nd gen)", "iPhone SE (3rd gen)"],
    "iPhone 6 Series": ["iPhone 6", "iPhone 6 Plus"],
    "iPhone 6s Series": ["iPhone 6s", "iPhone 6s Plus"],
    "iPhone 7 Series": ["iPhone 7", "iPhone 7 Plus"],
    "iPhone 8 Series": ["iPhone 8", "iPhone 8 Plus"],
    "iPhone X Series": ["iPhone X", "iPhone XR", "iPhone XS", "iPhone XS Max"],
    "iPhone 11 Series": ["iPhone 11", "iPhone 11 Pro", "iPhone 11 Pro Max"],
    "iPhone 12 Series": ["iPhone 12 mini", "iPhone 12", "iPhone 12 Pro", "iPhone 12 Pro Max"],
    "iPhone 13 Series": ["iPhone 13 mini", "iPhone 13", "iPhone 13 Pro", "iPhone 13 Pro Max"],
    "iPhone 14 Series": ["iPhone 14", "iPhone 14 Plus", "iPhone 14 Pro", "iPhone 14 Pro Max"],
    "iPhone 15 Series": ["iPhone 15", "iPhone 15 Plus", "iPhone 15 Pro", "iPhone 15 Pro Max"],
    "iPhone 16 Series": ["iPhone 16", "iPhone 16 Plus", "iPhone 16 Pro", "iPhone 16 Pro Max"],
  },
  SAMSUNG: {
    "Galaxy S Classic": ["Galaxy S (i9000)", "Galaxy S II", "Galaxy S III", "Galaxy S4", "Galaxy S5"],
    "Galaxy S6 Series": ["Galaxy S6", "Galaxy S6 Edge", "Galaxy S6 Edge+"],
    "Galaxy S7 Series": ["Galaxy S7", "Galaxy S7 Edge"],
    "Galaxy S8 Series": ["Galaxy S8", "Galaxy S8+"],
    "Galaxy S9 Series": ["Galaxy S9", "Galaxy S9+"],
    "Galaxy S10 Series": ["Galaxy S10e", "Galaxy S10", "Galaxy S10+", "Galaxy S10 5G"],
    "Galaxy S20 Series": ["Galaxy S20", "Galaxy S20+", "Galaxy S20 Ultra", "Galaxy S20 FE", "Galaxy S20 FE 5G"],
    "Galaxy S21 Series": ["Galaxy S21", "Galaxy S21+", "Galaxy S21 Ultra", "Galaxy S21 FE"],
    "Galaxy S22 Series": ["Galaxy S22", "Galaxy S22+", "Galaxy S22 Ultra"],
    "Galaxy S23 Series": ["Galaxy S23", "Galaxy S23+", "Galaxy S23 Ultra", "Galaxy S23 FE"],
    "Galaxy S24 Series": ["Galaxy S24", "Galaxy S24+", "Galaxy S24 Ultra", "Galaxy S24 FE"],
    "Galaxy S25 Series": ["Galaxy S25", "Galaxy S25+", "Galaxy S25 Ultra"],
    "Galaxy Note Classic": ["Galaxy Note", "Galaxy Note II", "Galaxy Note 3", "Galaxy Note 4", "Galaxy Note 5"],
    "Galaxy Note Modern": [
      "Galaxy Note 7",
      "Galaxy Note 8",
      "Galaxy Note 9",
      "Galaxy Note 10",
      "Galaxy Note 10+",
      "Galaxy Note 10 Lite",
      "Galaxy Note 20",
      "Galaxy Note 20 Ultra",
    ],
    "Galaxy A Series 2015-2018": [
      "Galaxy A3 (2015)",
      "Galaxy A5 (2015)",
      "Galaxy A7 (2015)",
      "Galaxy A3 (2016)",
      "Galaxy A5 (2016)",
      "Galaxy A7 (2016)",
      "Galaxy A3 (2017)",
      "Galaxy A5 (2017)",
      "Galaxy A7 (2017)",
      "Galaxy A6",
      "Galaxy A6+",
      "Galaxy A7 (2018)",
      "Galaxy A8 (2018)",
      "Galaxy A8+ (2018)",
      "Galaxy A9 (2018)",
    ],
    "Galaxy A Series 2019": [
      "Galaxy A10",
      "Galaxy A10e",
      "Galaxy A10s",
      "Galaxy A20",
      "Galaxy A20e",
      "Galaxy A20s",
      "Galaxy A30",
      "Galaxy A30s",
      "Galaxy A40",
      "Galaxy A50",
      "Galaxy A50s",
      "Galaxy A60",
      "Galaxy A70",
      "Galaxy A70s",
      "Galaxy A80",
      "Galaxy A90 5G",
    ],
    "Galaxy A Series 2020": [
      "Galaxy A01",
      "Galaxy A01 Core",
      "Galaxy A11",
      "Galaxy A21",
      "Galaxy A21s",
      "Galaxy A31",
      "Galaxy A41",
      "Galaxy A51",
      "Galaxy A51 5G",
      "Galaxy A71",
      "Galaxy A71 5G",
    ],
    "Galaxy A Series 2021": [
      "Galaxy A02",
      "Galaxy A02s",
      "Galaxy A12",
      "Galaxy A22",
      "Galaxy A22 5G",
      "Galaxy A32",
      "Galaxy A32 5G",
      "Galaxy A42 5G",
      "Galaxy A52",
      "Galaxy A52 5G",
      "Galaxy A52s 5G",
      "Galaxy A72",
    ],
    "Galaxy A Series 2022": [
      "Galaxy A03",
      "Galaxy A03 Core",
      "Galaxy A03s",
      "Galaxy A13",
      "Galaxy A13 5G",
      "Galaxy A23",
      "Galaxy A23 5G",
      "Galaxy A33 5G",
      "Galaxy A53 5G",
      "Galaxy A73 5G",
    ],
    "Galaxy A Series 2023": [
      "Galaxy A04",
      "Galaxy A04e",
      "Galaxy A04s",
      "Galaxy A14",
      "Galaxy A14 5G",
      "Galaxy A24",
      "Galaxy A34 5G",
      "Galaxy A54 5G",
      "Galaxy A74 5G",
    ],
    "Galaxy A Series 2024": [
      "Galaxy A05",
      "Galaxy A05s",
      "Galaxy A15",
      "Galaxy A15 5G",
      "Galaxy A25 5G",
      "Galaxy A35 5G",
      "Galaxy A55 5G",
      "Galaxy A06",
      "Galaxy A16 5G",
      "Galaxy A26 5G",
      "Galaxy A36 5G",
      "Galaxy A56 5G",
    ],
    "Galaxy M Series": [
      "Galaxy M10",
      "Galaxy M20",
      "Galaxy M30",
      "Galaxy M30s",
      "Galaxy M31",
      "Galaxy M31s",
      "Galaxy M32",
      "Galaxy M32 5G",
      "Galaxy M33 5G",
      "Galaxy M34 5G",
      "Galaxy M42 5G",
      "Galaxy M51",
      "Galaxy M52 5G",
      "Galaxy M53 5G",
      "Galaxy M54 5G",
      "Galaxy M55 5G",
    ],
    "Galaxy F Series": [
      "Galaxy F02s",
      "Galaxy F04",
      "Galaxy F12",
      "Galaxy F13",
      "Galaxy F14 5G",
      "Galaxy F22",
      "Galaxy F23 5G",
      "Galaxy F34 5G",
      "Galaxy F41",
      "Galaxy F42 5G",
      "Galaxy F52 5G",
      "Galaxy F54 5G",
      "Galaxy F55 5G",
      "Galaxy F62",
    ],
    "Galaxy Z Series": [
      "Galaxy Z Fold",
      "Galaxy Z Fold2",
      "Galaxy Z Fold3",
      "Galaxy Z Fold4",
      "Galaxy Z Fold5",
      "Galaxy Z Fold6",
      "Galaxy Z Flip",
      "Galaxy Z Flip 5G",
      "Galaxy Z Flip3",
      "Galaxy Z Flip4",
      "Galaxy Z Flip5",
      "Galaxy Z Flip6",
    ],
  },
  XIAOMI: {
    "Mi Classic": ["Mi 1", "Mi 1S", "Mi 2", "Mi 2A", "Mi 2S", "Mi 3", "Mi 4", "Mi 4c", "Mi 4i", "Mi 4s"],
    "Mi 5 Series": ["Mi 5", "Mi 5c", "Mi 5s", "Mi 5s Plus", "Mi 5X"],
    "Mi 6 Series": ["Mi 6", "Mi 6X", "Mi 6 Pro"],
    "Mi 8 Series": ["Mi 8", "Mi 8 Explorer", "Mi 8 Lite", "Mi 8 Pro", "Mi 8 SE", "Mi 8 Youth"],
    "Mi 9 Series": ["Mi 9", "Mi 9 Explorer", "Mi 9 Lite", "Mi 9 Pro", "Mi 9 SE", "Mi 9T", "Mi 9T Pro"],
    "Mi 10 Series": [
      "Mi 10",
      "Mi 10 Lite",
      "Mi 10 Pro",
      "Mi 10S",
      "Mi 10T",
      "Mi 10T Lite",
      "Mi 10T Pro",
      "Mi 10 Ultra",
    ],
    "Mi 11 Series": [
      "Mi 11",
      "Mi 11i",
      "Mi 11 Lite",
      "Mi 11 Lite 5G NE",
      "Mi 11 Pro",
      "Mi 11 Ultra",
      "Mi 11X",
      "Mi 11X Pro",
    ],
    "Mi 12 Series": [
      "Mi 12",
      "Mi 12 Lite",
      "Mi 12 Pro",
      "Mi 12S",
      "Mi 12S Pro",
      "Mi 12S Ultra",
      "Mi 12T",
      "Mi 12T Pro",
      "Mi 12X",
    ],
    "Mi 13 Series": ["Mi 13", "Mi 13 Lite", "Mi 13 Pro", "Mi 13T", "Mi 13T Pro", "Mi 13 Ultra"],
    "Mi 14 Series": ["Mi 14", "Mi 14 Pro", "Mi 14 Ultra", "Mi 14T", "Mi 14T Pro"],
    "Redmi Classic": [
      "Redmi 1S",
      "Redmi 2",
      "Redmi 2A",
      "Redmi 2 Prime",
      "Redmi 3",
      "Redmi 3A",
      "Redmi 3S",
      "Redmi 3S Prime",
      "Redmi 3X",
    ],
    "Redmi 4 Series": ["Redmi 4", "Redmi 4A", "Redmi 4 Prime", "Redmi 4X"],
    "Redmi 5 Series": ["Redmi 5", "Redmi 5A", "Redmi 5 Plus"],
    "Redmi 6 Series": ["Redmi 6", "Redmi 6A", "Redmi 6 Pro"],
    "Redmi 7 Series": ["Redmi 7", "Redmi 7A"],
    "Redmi 8 Series": ["Redmi 8", "Redmi 8A", "Redmi 8A Dual", "Redmi 8A Pro"],
    "Redmi 9 Series": [
      "Redmi 9",
      "Redmi 9A",
      "Redmi 9AT",
      "Redmi 9C",
      "Redmi 9i",
      "Redmi 9 Power",
      "Redmi 9 Prime",
      "Redmi 9T",
    ],
    "Redmi 10 Series": ["Redmi 10", "Redmi 10A", "Redmi 10C", "Redmi 10 Power", "Redmi 10 Prime"],
    "Redmi 11 Series": ["Redmi 11 Prime", "Redmi 11 Prime 5G"],
    "Redmi 12 Series": ["Redmi 12", "Redmi 12 5G", "Redmi 12C"],
    "Redmi 13 Series": ["Redmi 13C", "Redmi 13C 5G", "Redmi 13", "Redmi 13 5G"],
    "Redmi 14 Series": ["Redmi 14C", "Redmi 14C 5G"],
    "Redmi Note Classic": ["Redmi Note", "Redmi Note 2", "Redmi Note 3", "Redmi Note 4", "Redmi Note 4X"],
    "Redmi Note 5 Series": ["Redmi Note 5", "Redmi Note 5A", "Redmi Note 5A Prime", "Redmi Note 5 Pro"],
    "Redmi Note 6 Series": ["Redmi Note 6 Pro"],
    "Redmi Note 7 Series": ["Redmi Note 7", "Redmi Note 7 Pro", "Redmi Note 7S"],
    "Redmi Note 8 Series": ["Redmi Note 8", "Redmi Note 8 Pro", "Redmi Note 8T"],
    "Redmi Note 9 Series": [
      "Redmi Note 9",
      "Redmi Note 9 Pro",
      "Redmi Note 9 Pro Max",
      "Redmi Note 9S",
      "Redmi Note 9T",
    ],
    "Redmi Note 10 Series": [
      "Redmi Note 10",
      "Redmi Note 10 5G",
      "Redmi Note 10 Pro",
      "Redmi Note 10 Pro Max",
      "Redmi Note 10S",
      "Redmi Note 10T",
    ],
    "Redmi Note 11 Series": [
      "Redmi Note 11",
      "Redmi Note 11 Pro",
      "Redmi Note 11 Pro+ 5G",
      "Redmi Note 11S",
      "Redmi Note 11T 5G",
      "Redmi Note 11E Pro",
    ],
    "Redmi Note 12 Series": [
      "Redmi Note 12",
      "Redmi Note 12 5G",
      "Redmi Note 12 Pro",
      "Redmi Note 12 Pro+ 5G",
      "Redmi Note 12S",
      "Redmi Note 12T Pro",
      "Redmi Note 12 Turbo",
    ],
    "Redmi Note 13 Series": ["Redmi Note 13", "Redmi Note 13 5G", "Redmi Note 13 Pro", "Redmi Note 13 Pro+"],
  },
  POCO: {
    "POCO F Series": [
      "POCO F1",
      "POCO F2 Pro",
      "POCO F3",
      "POCO F3 GT",
      "POCO F4",
      "POCO F4 GT",
      "POCO F5",
      "POCO F5 Pro",
      "POCO F6",
      "POCO F6 Pro",
      "POCO F7",
      "POCO F7 Pro",
    ],
    "POCO X Series": [
      "POCO X2",
      "POCO X3",
      "POCO X3 NFC",
      "POCO X3 Pro",
      "POCO X3 GT",
      "POCO X4 GT",
      "POCO X4 Pro 5G",
      "POCO X5 5G",
      "POCO X5 Pro 5G",
      "POCO X6",
      "POCO X6 Pro",
      "POCO X6 Neo",
      "POCO X7",
      "POCO X7 Pro",
    ],
    "POCO M Series": [
      "POCO M2",
      "POCO M2 Pro",
      "POCO M2 Reloaded",
      "POCO M3",
      "POCO M3 Pro 5G",
      "POCO M4 5G",
      "POCO M4 Pro",
      "POCO M4 Pro 5G",
      "POCO M5",
      "POCO M5s",
      "POCO M5 4G",
      "POCO M6 5G",
      "POCO M6 Pro",
      "POCO M6 Pro 4G",
      "POCO M7 5G",
    ],
    "POCO C Series": [
      "POCO C3",
      "POCO C31",
      "POCO C40",
      "POCO C50",
      "POCO C51",
      "POCO C55",
      "POCO C61",
      "POCO C65",
      "POCO C75",
    ],
    "POCO T Series": ["POCO T1", "POCO T1 5G"],
    "POCO N Series": ["POCO N1", "POCO N1 Pro"],
  },
  "RED MAGIC": {
    "Red Magic Classic": ["Red Magic", "Red Magic Mars", "Red Magic 2"],
    "Red Magic 3 Series": ["Red Magic 3", "Red Magic 3S"],
    "Red Magic 5 Series": ["Red Magic 5G", "Red Magic 5S"],
    "Red Magic 6 Series": ["Red Magic 6", "Red Magic 6 Pro", "Red Magic 6S Pro", "Red Magic 6R"],
    "Red Magic 7 Series": ["Red Magic 7", "Red Magic 7 Pro", "Red Magic 7S", "Red Magic 7S Pro"],
    "Red Magic 8 Series": ["Red Magic 8 Pro", "Red Magic 8 Pro+", "Red Magic 8S Pro", "Red Magic 8S Pro+"],
    "Red Magic 9 Series": ["Red Magic 9 Pro", "Red Magic 9 Pro+", "Red Magic 9S Pro", "Red Magic 9S Pro+"],
    "Red Magic Nova Series": ["Red Magic Nova", "Red Magic Nova Gaming Tablet"],
    "Red Magic Titan Series": ["Red Magic Titan 16 Pro"],
  },
  HUAWEI: {
    "P Series Classic": ["Ascend P1", "Ascend P2", "Ascend P6", "Ascend P7", "P8", "P8 Lite", "P8 Max"],
    "P9 Series": ["P9", "P9 Lite", "P9 Plus"],
    "P10 Series": ["P10", "P10 Lite", "P10 Plus"],
    "P20 Series": ["P20", "P20 Lite", "P20 Pro"],
    "P30 Series": ["P30", "P30 Lite", "P30 Pro"],
    "P40 Series": ["P40", "P40 Lite", "P40 Lite E", "P40 Pro", "P40 Pro+"],
    "P50 Series": ["P50", "P50 Pro", "P50 Pocket"],
    "P60 Series": ["P60", "P60 Pro", "P60 Art"],
    "P70 Series": ["P70", "P70 Pro", "P70 Art"],
    "Mate Classic": ["Ascend Mate", "Ascend Mate 2", "Mate 7", "Mate 8"],
    "Mate 9 Series": ["Mate 9", "Mate 9 Lite", "Mate 9 Pro", "Mate 9 Porsche Design"],
    "Mate 10 Series": ["Mate 10", "Mate 10 Lite", "Mate 10 Pro", "Mate 10 Porsche Design"],
    "Mate 20 Series": [
      "Mate 20",
      "Mate 20 Lite",
      "Mate 20 Pro",
      "Mate 20 X",
      "Mate 20 X 5G",
      "Mate 20 RS Porsche Design",
    ],
    "Mate 30 Series": ["Mate 30", "Mate 30 Pro", "Mate 30 RS Porsche Design", "Mate 30E Pro 5G"],
    "Mate 40 Series": ["Mate 40", "Mate 40 Pro", "Mate 40 Pro+", "Mate 40E", "Mate 40 RS Porsche Design"],
    "Mate 50 Series": ["Mate 50", "Mate 50 Pro", "Mate 50 RS Porsche Design", "Mate 50E"],
    "Mate 60 Series": ["Mate 60", "Mate 60 Pro", "Mate 60 Pro+", "Mate 60 RS Ultimate"],
    "Mate 70 Series": ["Mate 70", "Mate 70 Pro", "Mate 70 Pro+", "Mate 70 RS Ultimate"],
    "Nova Classic": ["Nova", "Nova Plus"],
    "Nova 2 Series": ["Nova 2", "Nova 2 Plus", "Nova 2i", "Nova 2s"],
    "Nova 3 Series": ["Nova 3", "Nova 3e", "Nova 3i"],
    "Nova 4 Series": ["Nova 4", "Nova 4e"],
    "Nova 5 Series": ["Nova 5", "Nova 5 Pro", "Nova 5T", "Nova 5i", "Nova 5i Pro", "Nova 5z"],
    "Nova 6 Series": ["Nova 6", "Nova 6 5G", "Nova 6 SE"],
    "Nova 7 Series": ["Nova 7", "Nova 7 5G", "Nova 7 Pro 5G", "Nova 7 SE", "Nova 7i"],
    "Nova 8 Series": ["Nova 8", "Nova 8 5G", "Nova 8 Pro 5G", "Nova 8 SE"],
    "Nova 9 Series": ["Nova 9", "Nova 9 Pro", "Nova 9 SE"],
    "Nova 10 Series": ["Nova 10", "Nova 10 Pro", "Nova 10 SE", "Nova 10 Youth"],
    "Nova 11 Series": ["Nova 11", "Nova 11 Pro", "Nova 11 SE", "Nova 11i"],
    "Nova 12 Series": ["Nova 12", "Nova 12 Pro", "Nova 12 SE", "Nova 12i", "Nova 12 Ultra"],
    "Y Series": [
      "Y3 (2017)",
      "Y5 (2017)",
      "Y6 (2017)",
      "Y7 (2017)",
      "Y9 (2017)",
      "Y3 (2018)",
      "Y5 (2018)",
      "Y6 (2018)",
      "Y7 (2018)",
      "Y9 (2018)",
      "Y5 (2019)",
      "Y6 (2019)",
      "Y7 (2019)",
      "Y9 (2019)",
      "Y9 Prime (2019)",
      "Y5p",
      "Y6p",
      "Y7a",
      "Y8p",
      "Y9a",
      "Y70",
      "Y90",
    ],
  },
  HONOR: {
    "Honor Classic": ["Honor 3C", "Honor 3X", "Honor 4A", "Honor 4C", "Honor 4X"],
    "Honor 5 Series": ["Honor 5A", "Honor 5C", "Honor 5X"],
    "Honor 6 Series": ["Honor 6", "Honor 6 Plus", "Honor 6A", "Honor 6C", "Honor 6X"],
    "Honor 7 Series": ["Honor 7", "Honor 7 Enhanced", "Honor 7A", "Honor 7C", "Honor 7S", "Honor 7X"],
    "Honor 8 Series": [
      "Honor 8",
      "Honor 8 Lite",
      "Honor 8 Pro",
      "Honor 8A",
      "Honor 8C",
      "Honor 8S",
      "Honor 8X",
      "Honor 8X Max",
    ],
    "Honor 9 Series": [
      "Honor 9",
      "Honor 9 Lite",
      "Honor 9N",
      "Honor 9A",
      "Honor 9C",
      "Honor 9S",
      "Honor 9X",
      "Honor 9X Pro",
    ],
    "Honor 10 Series": ["Honor 10", "Honor 10 Lite", "Honor 10i", "Honor 10X", "Honor 10X Lite", "Honor 10X Pro"],
    "Honor 20 Series": ["Honor 20", "Honor 20 Lite", "Honor 20 Pro", "Honor 20S", "Honor 20i"],
    "Honor 30 Series": ["Honor 30", "Honor 30 Pro", "Honor 30 Pro+", "Honor 30S", "Honor 30i"],
    "Honor 50 Series": ["Honor 50", "Honor 50 Lite", "Honor 50 Pro", "Honor 50 SE"],
    "Honor 60 Series": ["Honor 60", "Honor 60 Pro", "Honor 60 SE"],
    "Honor 70 Series": ["Honor 70", "Honor 70 Pro", "Honor 70 Pro+"],
    "Honor 80 Series": ["Honor 80", "Honor 80 Pro", "Honor 80 SE", "Honor 80 GT"],
    "Honor 90 Series": ["Honor 90", "Honor 90 Pro", "Honor 90 GT", "Honor 90 Lite"],
    "Honor 100 Series": ["Honor 100", "Honor 100 Pro"],
    "Honor 200 Series": ["Honor 200", "Honor 200 Pro", "Honor 200 Lite"],
    "Honor Magic Series": [
      "Honor Magic",
      "Honor Magic 2",
      "Honor Magic 3",
      "Honor Magic 3 Pro+",
      "Honor Magic 4",
      "Honor Magic 4 Pro",
      "Honor Magic 4 Ultimate",
      "Honor Magic 5",
      "Honor Magic 5 Pro",
      "Honor Magic 6",
      "Honor Magic 6 Pro",
      "Honor Magic 7",
      "Honor Magic 7 Pro",
    ],
    "Honor Play Series": [
      "Honor Play",
      "Honor Play 3",
      "Honor Play 3e",
      "Honor Play 4",
      "Honor Play 4 Pro",
      "Honor Play 4T",
      "Honor Play 4T Pro",
      "Honor Play 5",
      "Honor Play 5T",
      "Honor Play 5T Pro",
      "Honor Play 6T",
      "Honor Play 6T Pro",
      "Honor Play 7T",
      "Honor Play 7T Pro",
      "Honor Play 8T",
      "Honor Play 40",
      "Honor Play 50",
    ],
    "Honor X Series": [
      "Honor X6",
      "Honor X7",
      "Honor X7a",
      "Honor X8",
      "Honor X8a",
      "Honor X8b",
      "Honor X9",
      "Honor X9a",
      "Honor X9b",
      "Honor X10",
      "Honor X20",
      "Honor X30",
      "Honor X40",
      "Honor X50",
    ],
  },
  GOOGLE: {
    "Pixel Classic": ["Pixel", "Pixel XL"],
    "Pixel 2 Series": ["Pixel 2", "Pixel 2 XL"],
    "Pixel 3 Series": ["Pixel 3", "Pixel 3 XL", "Pixel 3a", "Pixel 3a XL"],
    "Pixel 4 Series": ["Pixel 4", "Pixel 4 XL", "Pixel 4a", "Pixel 4a 5G"],
    "Pixel 5 Series": ["Pixel 5", "Pixel 5a"],
    "Pixel 6 Series": ["Pixel 6", "Pixel 6 Pro", "Pixel 6a"],
    "Pixel 7 Series": ["Pixel 7", "Pixel 7 Pro", "Pixel 7a"],
    "Pixel 8 Series": ["Pixel 8", "Pixel 8 Pro", "Pixel 8a"],
    "Pixel 9 Series": ["Pixel 9", "Pixel 9 Pro", "Pixel 9 Pro XL", "Pixel 9a"],
    "Pixel Fold Series": ["Pixel Fold", "Pixel Fold 2"],
    "Pixel Tablet": ["Pixel Tablet"],
  },
  PHOENIX: {
    "Phoenix Classic": ["Phoenix 1", "Phoenix 2", "Phoenix 3"],
    "Phoenix Pro": ["Phoenix Pro", "Phoenix Pro 2", "Phoenix Pro 3"],
    "Phoenix Max": ["Phoenix Max", "Phoenix Max 2"],
    "Phoenix Lite": ["Phoenix Lite", "Phoenix Lite 2", "Phoenix Lite 3"],
    "Phoenix Gaming": ["Phoenix Gaming", "Phoenix Gaming Pro", "Phoenix Gaming Max"],
    "Phoenix Ultra": ["Phoenix Ultra", "Phoenix Ultra Pro"],
  },
  LENOVO: {
    "Lenovo A Series": ["A1000", "A2010", "A5000", "A6000", "A6000 Plus", "A6010", "A6020", "A7000", "A7010", "A7700"],
    "Lenovo K Series": [
      "K3",
      "K3 Note",
      "K4 Note",
      "K5",
      "K5 Note",
      "K5 Plus",
      "K6",
      "K6 Note",
      "K6 Power",
      "K8",
      "K8 Note",
      "K8 Plus",
      "K9",
      "K10 Note",
      "K12",
      "K12 Pro",
      "K13",
      "K13 Pro",
      "K14",
      "K15",
    ],
    "Lenovo P Series": ["P1", "P1m", "P2", "P70", "P90"],
    "Lenovo S Series": ["S60", "S90", "S850", "S860", "S880", "S920", "S930", "S960"],
    "Lenovo Z Series": ["Z2", "Z2 Plus", "Z5", "Z5 Pro", "Z5 Pro GT", "Z5s", "Z6", "Z6 Lite", "Z6 Pro", "Z6 Youth"],
    "Lenovo Legion": ["Legion Phone Duel", "Legion Phone Duel 2", "Legion Y70", "Legion Y90", "Legion Pro"],
    "Lenovo Vibe": [
      "Vibe C",
      "Vibe C2",
      "Vibe K4 Note",
      "Vibe K5",
      "Vibe K5 Note",
      "Vibe K5 Plus",
      "Vibe P1",
      "Vibe P1m",
      "Vibe P2",
      "Vibe S1",
      "Vibe Shot",
      "Vibe X2",
      "Vibe X3",
      "Vibe Z2 Pro",
    ],
  },
  MOTOROLA: {
    "Moto C Series": ["Moto C", "Moto C Plus"],
    "Moto G Classic": ["Moto G (1st gen)", "Moto G (2nd gen)", "Moto G (3rd gen)"],
    "Moto G4 Series": ["Moto G4", "Moto G4 Play", "Moto G4 Plus"],
    "Moto G5 Series": ["Moto G5", "Moto G5 Plus", "Moto G5S", "Moto G5S Plus"],
    "Moto G6 Series": ["Moto G6", "Moto G6 Play", "Moto G6 Plus"],
    "Moto G7 Series": ["Moto G7", "Moto G7 Play", "Moto G7 Plus", "Moto G7 Power"],
    "Moto G8 Series": ["Moto G8", "Moto G8 Play", "Moto G8 Plus", "Moto G8 Power", "Moto G8 Power Lite"],
    "Moto G9 Series": ["Moto G9", "Moto G9 Play", "Moto G9 Plus", "Moto G9 Power"],
    "Moto G10-G20": [
      "Moto G10",
      "Moto G10 Power",
      "Moto G20",
      "Moto G30",
      "Moto G40 Fusion",
      "Moto G50",
      "Moto G60",
      "Moto G60s",
    ],
    "Moto G30-G100": [
      "Moto G31",
      "Moto G32",
      "Moto G41",
      "Moto G42",
      "Moto G51 5G",
      "Moto G52",
      "Moto G62 5G",
      "Moto G71 5G",
      "Moto G72",
      "Moto G82 5G",
      "Moto G100",
    ],
    "Moto G 2023-2024": [
      "Moto G13",
      "Moto G14",
      "Moto G23",
      "Moto G24",
      "Moto G34 5G",
      "Moto G53",
      "Moto G54 5G",
      "Moto G73 5G",
      "Moto G84 5G",
      "Moto G85 5G",
    ],
    "Moto E Classic": ["Moto E (1st gen)", "Moto E (2nd gen)"],
    "Moto E4-E7": [
      "Moto E4",
      "Moto E4 Plus",
      "Moto E5",
      "Moto E5 Play",
      "Moto E5 Plus",
      "Moto E6",
      "Moto E6 Play",
      "Moto E6 Plus",
      "Moto E6s",
      "Moto E7",
      "Moto E7 Plus",
      "Moto E7 Power",
      "Moto E7i Power",
    ],
    "Moto E 2022-2024": ["Moto E13", "Moto E22", "Moto E22i", "Moto E22s", "Moto E32", "Moto E32s", "Moto E40"],
    "Moto X Series": [
      "Moto X (1st gen)",
      "Moto X (2nd gen)",
      "Moto X Force",
      "Moto X Play",
      "Moto X Pure Edition",
      "Moto X Style",
      "Moto X4",
    ],
    "Moto Z Series": [
      "Moto Z",
      "Moto Z Droid",
      "Moto Z Force",
      "Moto Z Force Droid",
      "Moto Z Play",
      "Moto Z2 Force",
      "Moto Z2 Play",
      "Moto Z3",
      "Moto Z3 Play",
      "Moto Z4",
    ],
    "Moto Edge Series": [
      "Moto Edge",
      "Moto Edge+",
      "Moto Edge 20",
      "Moto Edge 20 Fusion",
      "Moto Edge 20 Lite",
      "Moto Edge 20 Pro",
      "Moto Edge 30",
      "Moto Edge 30 Fusion",
      "Moto Edge 30 Neo",
      "Moto Edge 30 Pro",
      "Moto Edge 30 Ultra",
      "Moto Edge 40",
      "Moto Edge 40 Neo",
      "Moto Edge 40 Pro",
      "Moto Edge 50",
      "Moto Edge 50 Pro",
    ],
    "Moto One Series": [
      "Moto One",
      "Moto One Action",
      "Moto One Fusion",
      "Moto One Fusion+",
      "Moto One Hyper",
      "Moto One Macro",
      "Moto One Power",
      "Moto One Vision",
      "Moto One Zoom",
      "Moto One 5G Ace",
    ],
    "Moto C Series": ["Moto C", "Moto C Plus"],
    "Moto Razr Series": ["Moto Razr (2019)", "Moto Razr 5G", "Moto Razr (2022)", "Moto Razr 40", "Moto Razr 40 Ultra"],
    "Moto A Series": ["Moto A1", "Moto A10", "Moto A11", "Moto A12", "Moto A13", "Moto A14", "Moto A15"],
    "Moto P Series": ["Moto P30", "Moto P30 Note", "Moto P30 Play", "Moto P40", "Moto P50"],
    "Moto S Series": ["Moto S30 Pro", "Moto S50 Neo"],
  },
  ONEPLUS: {
    "OnePlus Classic": ["OnePlus One", "OnePlus 2", "OnePlus X"],
    "OnePlus 3 Series": ["OnePlus 3", "OnePlus 3T"],
    "OnePlus 5 Series": ["OnePlus 5", "OnePlus 5T"],
    "OnePlus 6 Series": ["OnePlus 6", "OnePlus 6T"],
    "OnePlus 7 Series": ["OnePlus 7", "OnePlus 7 Pro", "OnePlus 7T", "OnePlus 7T Pro", "OnePlus 7T Pro 5G McLaren"],
    "OnePlus 8 Series": ["OnePlus 8", "OnePlus 8 Pro", "OnePlus 8T"],
    "OnePlus 9 Series": ["OnePlus 9", "OnePlus 9 Pro", "OnePlus 9R", "OnePlus 9RT"],
    "OnePlus 10 Series": ["OnePlus 10 Pro", "OnePlus 10R", "OnePlus 10T"],
    "OnePlus 11 Series": ["OnePlus 11", "OnePlus 11R"],
    "OnePlus 12 Series": ["OnePlus 12", "OnePlus 12R"],
    "OnePlus 13 Series": ["OnePlus 13", "OnePlus 13R"],
    "OnePlus Nord Classic": ["OnePlus Nord", "OnePlus Nord N10 5G", "OnePlus Nord N100"],
    "OnePlus Nord 2 Series": ["OnePlus Nord 2", "OnePlus Nord 2T"],
    "OnePlus Nord CE Series": [
      "OnePlus Nord CE",
      "OnePlus Nord CE 2",
      "OnePlus Nord CE 2 Lite",
      "OnePlus Nord CE 3",
      "OnePlus Nord CE 3 Lite",
      "OnePlus Nord CE 4",
    ],
    "OnePlus Nord 3 Series": ["OnePlus Nord 3", "OnePlus Nord 4"],
    "OnePlus Nord N Series": ["OnePlus Nord N200", "OnePlus Nord N20", "OnePlus Nord N300"],
  },
  OPPO: {
    "Find Classic": ["Find 5", "Find 7", "Find 7a"],
    "Find X Series": [
      "Find X",
      "Find X Lamborghini",
      "Find X2",
      "Find X2 Lite",
      "Find X2 Neo",
      "Find X2 Pro",
      "Find X3",
      "Find X3 Lite",
      "Find X3 Neo",
      "Find X3 Pro",
      "Find X5",
      "Find X5 Lite",
      "Find X5 Pro",
      "Find X6",
      "Find X6 Pro",
      "Find X7",
      "Find X7 Ultra",
      "Find X8",
      "Find X8 Pro",
    ],
    "Reno Classic": ["Reno", "Reno 10x Zoom"],
    "Reno 2 Series": ["Reno 2", "Reno 2F", "Reno 2Z"],
    "Reno 3 Series": ["Reno 3", "Reno 3 Pro", "Reno 3 Pro 5G"],
    "Reno 4 Series": ["Reno 4", "Reno 4 Lite", "Reno 4 Pro", "Reno 4 Pro 5G", "Reno 4 SE", "Reno 4Z"],
    "Reno 5 Series": [
      "Reno 5",
      "Reno 5 4G",
      "Reno 5 5G",
      "Reno 5 Lite",
      "Reno 5 Pro",
      "Reno 5 Pro 5G",
      "Reno 5 Pro+",
      "Reno 5F",
      "Reno 5K",
      "Reno 5Z",
    ],
    "Reno 6 Series": [
      "Reno 6",
      "Reno 6 4G",
      "Reno 6 5G",
      "Reno 6 Lite",
      "Reno 6 Pro",
      "Reno 6 Pro 5G",
      "Reno 6 Pro+",
      "Reno 6Z",
    ],
    "Reno 7 Series": [
      "Reno 7",
      "Reno 7 4G",
      "Reno 7 5G",
      "Reno 7 Lite",
      "Reno 7 Pro",
      "Reno 7 Pro 5G",
      "Reno 7A",
      "Reno 7Z",
    ],
    "Reno 8 Series": [
      "Reno 8",
      "Reno 8 4G",
      "Reno 8 5G",
      "Reno 8 Lite",
      "Reno 8 Pro",
      "Reno 8 Pro+",
      "Reno 8T",
      "Reno 8Z",
    ],
    "Reno 9 Series": ["Reno 9", "Reno 9 Pro", "Reno 9 Pro+"],
    "Reno 10 Series": ["Reno 10", "Reno 10 Pro", "Reno 10 Pro+", "Reno 10x Zoom"],
    "Reno 11 Series": ["Reno 11", "Reno 11 5G", "Reno 11 Pro", "Reno 11F"],
    "Reno 12 Series": ["Reno 12", "Reno 12 Pro", "Reno 12F", "Reno 12 5G"],
    "A Series 2018-2019": ["A1", "A1k", "A3s", "A5", "A5s", "A7", "A7n", "A9", "A9 2020", "A11", "A11k", "A12", "A12e"],
    "A Series 2020": [
      "A15",
      "A15s",
      "A16",
      "A16k",
      "A16s",
      "A31",
      "A31 2020",
      "A32",
      "A33",
      "A52",
      "A53",
      "A72",
      "A73",
      "A74",
      "A91",
      "A92",
      "A92s",
      "A93",
      "A94",
      "A95",
    ],
    "A Series 2021-2022": ["A54", "A55", "A56", "A57", "A76", "A77", "A78", "A96", "A97", "A98"],
    "A Series 2023-2024": ["A17", "A17k", "A18", "A38", "A58", "A59", "A79", "A99"],
    "F Series": [
      "F1",
      "F1 Plus",
      "F1s",
      "F3",
      "F3 Plus",
      "F5",
      "F5 Youth",
      "F7",
      "F7 Youth",
      "F9",
      "F9 Pro",
      "F11",
      "F11 Pro",
      "F15",
      "F17",
      "F17 Pro",
      "F19",
      "F19 Pro",
      "F19 Pro+",
      "F19s",
      "F21 Pro",
      "F21 Pro 5G",
      "F23 5G",
      "F25 Pro 5G",
    ],
    "K Series": [
      "K1",
      "K3",
      "K5",
      "K7",
      "K7x",
      "K9",
      "K9 Pro",
      "K9x",
      "K10",
      "K10 Pro",
      "K10x",
      "K11",
      "K11x",
      "K12",
      "K12x",
    ],
    "R Series": [
      "R1",
      "R1C",
      "R1S",
      "R3",
      "R5",
      "R5s",
      "R7",
      "R7 Lite",
      "R7 Plus",
      "R7s",
      "R9",
      "R9 Plus",
      "R9s",
      "R9s Plus",
      "R11",
      "R11 Plus",
      "R11s",
      "R11s Plus",
      "R15",
      "R15 Pro",
      "R17",
      "R17 Neo",
      "R17 Pro",
    ],
  },
  REALME: {
    "Realme Classic": ["Realme 1", "Realme 2", "Realme 2 Pro"],
    "Realme 3 Series": ["Realme 3", "Realme 3 Pro", "Realme 3i"],
    "Realme 5 Series": ["Realme 5", "Realme 5 Pro", "Realme 5i", "Realme 5s"],
    "Realme 6 Series": ["Realme 6", "Realme 6 Pro", "Realme 6i", "Realme 6s"],
    "Realme 7 Series": ["Realme 7", "Realme 7 Pro", "Realme 7i", "Realme 7 5G"],
    "Realme 8 Series": ["Realme 8", "Realme 8 Pro", "Realme 8i", "Realme 8s 5G", "Realme 8 5G"],
    "Realme 9 Series": ["Realme 9", "Realme 9 Pro", "Realme 9 Pro+", "Realme 9i", "Realme 9 5G", "Realme 9 4G"],
    "Realme 10 Series": ["Realme 10", "Realme 10 Pro", "Realme 10 Pro+", "Realme 10s", "Realme 10 4G", "Realme 10 5G"],
    "Realme 11 Series": ["Realme 11", "Realme 11 Pro", "Realme 11 Pro+", "Realme 11x", "Realme 11 4G", "Realme 11 5G"],
    "Realme 12 Series": ["Realme 12", "Realme 12 Pro", "Realme 12 Pro+", "Realme 12x", "Realme 12 4G", "Realme 12 5G"],
    "Realme 13 Series": ["Realme 13", "Realme 13 Pro", "Realme 13 Pro+", "Realme 13 5G"],
    "Realme GT Series": [
      "Realme GT",
      "Realme GT Master Edition",
      "Realme GT Explorer Master",
      "Realme GT Neo",
      "Realme GT Neo 2",
      "Realme GT Neo 2T",
      "Realme GT Neo 3",
      "Realme GT Neo 3T",
      "Realme GT Neo 5",
      "Realme GT Neo 5 SE",
      "Realme GT 2",
      "Realme GT 2 Pro",
      "Realme GT 3",
      "Realme GT 5",
      "Realme GT 5 Pro",
      "Realme GT 6",
      "Realme GT 7 Pro",
    ],
    "Realme C Series": [
      "Realme C1",
      "Realme C1 2019",
      "Realme C2",
      "Realme C3",
      "Realme C11",
      "Realme C11 2021",
      "Realme C12",
      "Realme C15",
      "Realme C17",
      "Realme C20",
      "Realme C20A",
      "Realme C21",
      "Realme C21Y",
      "Realme C25",
      "Realme C25s",
      "Realme C25Y",
      "Realme C30",
      "Realme C30s",
      "Realme C31",
      "Realme C33",
      "Realme C35",
      "Realme C53",
      "Realme C55",
      "Realme C67",
      "Realme C75",
    ],
    "Realme Narzo Series": [
      "Realme Narzo 10",
      "Realme Narzo 10A",
      "Realme Narzo 20",
      "Realme Narzo 20 Pro",
      "Realme Narzo 20A",
      "Realme Narzo 30",
      "Realme Narzo 30 Pro",
      "Realme Narzo 30A",
      "Realme Narzo 30 4G",
      "Realme Narzo 30 5G",
      "Realme Narzo 50",
      "Realme Narzo 50 Pro",
      "Realme Narzo 50A",
      "Realme Narzo 50A Prime",
      "Realme Narzo 50i",
      "Realme Narzo 50i Prime",
      "Realme Narzo 60",
      "Realme Narzo 60 Pro",
      "Realme Narzo 60x",
      "Realme Narzo 70",
      "Realme Narzo 70 Pro",
    ],
    "Realme V Series": [
      "Realme V3",
      "Realme V5",
      "Realme V11",
      "Realme V11s",
      "Realme V13",
      "Realme V15",
      "Realme V20",
      "Realme V21",
      "Realme V23",
      "Realme V25",
      "Realme V30",
      "Realme V40",
      "Realme V50",
    ],
    "Realme Q Series": [
      "Realme Q",
      "Realme Q2",
      "Realme Q2 Pro",
      "Realme Q2i",
      "Realme Q3",
      "Realme Q3 Pro",
      "Realme Q3i",
      "Realme Q3s",
      "Realme Q3t",
      "Realme Q5",
      "Realme Q5 Pro",
      "Realme Q5i",
      "Realme Q5x",
    ],
    "Realme X Series": [
      "Realme X",
      "Realme X Lite",
      "Realme X2",
      "Realme X2 Pro",
      "Realme X3",
      "Realme X3 SuperZoom",
      "Realme X7",
      "Realme X7 Pro",
      "Realme X7 Max",
      "Realme X50",
      "Realme X50 Pro",
      "Realme X50 Pro Player",
      "Realme X50m",
      "Realme XT",
    ],
  },
  VIVO: {
    "Vivo Y Series": [
      "Vivo Y11",
      "Vivo Y12",
      "Vivo Y15",
      "Vivo Y17",
      "Vivo Y19",
      "Vivo Y20",
      "Vivo Y21",
      "Vivo Y22",
      "Vivo Y27",
      "Vivo Y28",
      "Vivo Y30",
      "Vivo Y31",
      "Vivo Y33",
      "Vivo Y35",
      "Vivo Y36",
      "Vivo Y50",
      "Vivo Y51",
      "Vivo Y53",
      "Vivo Y55",
      "Vivo Y56",
      "Vivo Y70",
      "Vivo Y71",
      "Vivo Y72",
      "Vivo Y73",
      "Vivo Y75",
      "Vivo Y76",
      "Vivo Y77",
      "Vivo Y78",
      "Vivo Y81",
      "Vivo Y83",
      "Vivo Y85",
      "Vivo Y91",
      "Vivo Y93",
      "Vivo Y95",
      "Vivo Y100",
    ],
    "Vivo V Series": [
      "Vivo V3",
      "Vivo V3 Max",
      "Vivo V5",
      "Vivo V5 Plus",
      "Vivo V5s",
      "Vivo V7",
      "Vivo V7+",
      "Vivo V9",
      "Vivo V9 Youth",
      "Vivo V11",
      "Vivo V11 Pro",
      "Vivo V15",
      "Vivo V15 Pro",
      "Vivo V17",
      "Vivo V17 Pro",
      "Vivo V19",
      "Vivo V20",
      "Vivo V20 Pro",
      "Vivo V20 SE",
      "Vivo V21",
      "Vivo V21 5G",
      "Vivo V21e",
      "Vivo V23",
      "Vivo V23 5G",
      "Vivo V23 Pro",
      "Vivo V23e",
      "Vivo V25",
      "Vivo V25 5G",
      "Vivo V25 Pro",
      "Vivo V25e",
      "Vivo V27",
      "Vivo V27 5G",
      "Vivo V27 Pro",
      "Vivo V27e",
      "Vivo V29",
      "Vivo V29 5G",
      "Vivo V29 Pro",
      "Vivo V29e",
      "Vivo V30",
      "Vivo V30 5G",
      "Vivo V30 Pro",
      "Vivo V30e",
    ],
    "Vivo X Series": [
      "Vivo X3",
      "Vivo X5",
      "Vivo X5 Max",
      "Vivo X5 Pro",
      "Vivo X6",
      "Vivo X6 Plus",
      "Vivo X7",
      "Vivo X7 Plus",
      "Vivo X9",
      "Vivo X9 Plus",
      "Vivo X9s",
      "Vivo X9s Plus",
      "Vivo X20",
      "Vivo X20 Plus",
      "Vivo X21",
      "Vivo X21 UD",
      "Vivo X23",
      "Vivo X27",
      "Vivo X30",
      "Vivo X30 Pro",
      "Vivo X50",
      "Vivo X50 Pro",
      "Vivo X50 Pro+",
      "Vivo X60",
      "Vivo X60 Pro",
      "Vivo X60 Pro+",
      "Vivo X70",
      "Vivo X70 Pro",
      "Vivo X70 Pro+",
      "Vivo X80",
      "Vivo X80 Pro",
      "Vivo X90",
      "Vivo X90 Pro",
      "Vivo X90 Pro+",
      "Vivo X100",
      "Vivo X100 Pro",
      "Vivo X100 Ultra",
    ],
    "Vivo S Series": [
      "Vivo S1",
      "Vivo S1 Pro",
      "Vivo S5",
      "Vivo S6",
      "Vivo S7",
      "Vivo S7e",
      "Vivo S9",
      "Vivo S9e",
      "Vivo S10",
      "Vivo S10 Pro",
      "Vivo S10e",
      "Vivo S12",
      "Vivo S12 Pro",
      "Vivo S15",
      "Vivo S15 Pro",
      "Vivo S16",
      "Vivo S16 Pro",
      "Vivo S17",
      "Vivo S17 Pro",
      "Vivo S18",
      "Vivo S18 Pro",
      "Vivo S19",
      "Vivo S19 Pro",
    ],
    "Vivo iQOO Series": [
      "iQOO",
      "iQOO Pro",
      "iQOO Pro 5G",
      "iQOO Neo",
      "iQOO Neo 855",
      "iQOO Neo3",
      "iQOO 3",
      "iQOO 3 5G",
      "iQOO U1",
      "iQOO Z1",
      "iQOO Z1x",
      "iQOO 5",
      "iQOO 5 Pro",
      "iQOO U3",
      "iQOO 7",
      "iQOO 7 Legend",
      "iQOO Neo5",
      "iQOO 8",
      "iQOO 8 Pro",
      "iQOO 9",
      "iQOO 9 Pro",
      "iQOO Neo6",
      "iQOO 10",
      "iQOO 10 Pro",
      "iQOO Neo7",
      "iQOO 11",
      "iQOO 11 Pro",
      "iQOO Neo8",
      "iQOO 12",
      "iQOO 12 Pro",
    ],
  },
  ASUS: {
    "ROG Phone Series": [
      "ROG Phone",
      "ROG Phone II",
      "ROG Phone 3",
      "ROG Phone 3 Strix",
      "ROG Phone 5",
      "ROG Phone 5 Pro",
      "ROG Phone 5 Ultimate",
      "ROG Phone 5s",
      "ROG Phone 5s Pro",
      "ROG Phone 6",
      "ROG Phone 6 Pro",
      "ROG Phone 6D",
      "ROG Phone 6D Ultimate",
      "ROG Phone 7",
      "ROG Phone 7 Pro",
      "ROG Phone 7 Ultimate",
      "ROG Phone 8",
      "ROG Phone 8 Pro",
      "ROG Phone 8 Ultimate",
    ],
    "Zenfone Series": [
      "Zenfone 2",
      "Zenfone 3",
      "Zenfone 3 Max",
      "Zenfone 3 Zoom",
      "Zenfone 4",
      "Zenfone 4 Max",
      "Zenfone 4 Pro",
      "Zenfone 4 Selfie",
      "Zenfone 5",
      "Zenfone 5 Lite",
      "Zenfone 5Z",
      "Zenfone 6",
      "Zenfone 7",
      "Zenfone 7 Pro",
      "Zenfone 8",
      "Zenfone 8 Flip",
      "Zenfone 9",
      "Zenfone 10",
      "Zenfone 11 Ultra",
    ],
    "Zenfone Max Series": [
      "Zenfone Max",
      "Zenfone Max Pro M1",
      "Zenfone Max Pro M2",
      "Zenfone Max Shot",
      "Zenfone Max Plus M1",
      "Zenfone Max Plus M2",
    ],
  },
  "BLACK SHARK": {
    "Black Shark Classic": ["Black Shark", "Black Shark Helo"],
    "Black Shark 2 Series": ["Black Shark 2", "Black Shark 2 Pro"],
    "Black Shark 3 Series": ["Black Shark 3", "Black Shark 3 Pro", "Black Shark 3S"],
    "Black Shark 4 Series": ["Black Shark 4", "Black Shark 4 Pro", "Black Shark 4S"],
    "Black Shark 5 Series": ["Black Shark 5", "Black Shark 5 Pro", "Black Shark 5 RS"],
  },
  NOTHING: {
    "Nothing Phone Series": ["Nothing Phone (1)", "Nothing Phone (2)", "Nothing Phone (2a)", "Nothing Phone (2a) Plus"],
  },
  SONY: {
    "Xperia 1 Series": ["Xperia 1", "Xperia 1 II", "Xperia 1 III", "Xperia 1 IV", "Xperia 1 V", "Xperia 1 VI"],
    "Xperia 5 Series": ["Xperia 5", "Xperia 5 II", "Xperia 5 III", "Xperia 5 IV", "Xperia 5 V"],
    "Xperia 10 Series": ["Xperia 10", "Xperia 10 II", "Xperia 10 III", "Xperia 10 IV", "Xperia 10 V", "Xperia 10 VI"],
    "Xperia Pro Series": ["Xperia Pro", "Xperia Pro-I"],
    "Xperia L Series": ["Xperia L1", "Xperia L2", "Xperia L3", "Xperia L4"],
    "Xperia XA Series": [
      "Xperia XA",
      "Xperia XA1",
      "Xperia XA1 Plus",
      "Xperia XA1 Ultra",
      "Xperia XA2",
      "Xperia XA2 Plus",
      "Xperia XA2 Ultra",
    ],
    "Xperia XZ Series": [
      "Xperia XZ",
      "Xperia XZ1",
      "Xperia XZ1 Compact",
      "Xperia XZ2",
      "Xperia XZ2 Compact",
      "Xperia XZ2 Premium",
      "Xperia XZ3",
    ],
    "Xperia Z Series": [
      "Xperia Z",
      "Xperia Z1",
      "Xperia Z1 Compact",
      "Xperia Z2",
      "Xperia Z3",
      "Xperia Z3 Compact",
      "Xperia Z4",
      "Xperia Z5",
      "Xperia Z5 Compact",
      "Xperia Z5 Premium",
    ],
  },
  LG: {
    "G Series": ["G2", "G3", "G4", "G5", "G6", "G7 ThinQ", "G8 ThinQ", "G8s ThinQ"],
    "V Series": ["V10", "V20", "V30", "V30+", "V35 ThinQ", "V40 ThinQ", "V50 ThinQ", "V60 ThinQ"],
    "K Series": [
      "K4",
      "K7",
      "K8",
      "K10",
      "K11",
      "K20",
      "K22",
      "K30",
      "K40",
      "K41S",
      "K42",
      "K50",
      "K51S",
      "K52",
      "K61",
      "K62",
    ],
    "Q Series": ["Q6", "Q7", "Q8", "Q60", "Q61", "Q70", "Q92"],
    "Stylo Series": ["Stylo 4", "Stylo 5", "Stylo 6", "Stylo 7"],
    "Wing Series": ["Wing"],
    "Velvet Series": ["Velvet", "Velvet 5G"],
  },
  HTC: {
    "U Series": ["U11", "U11+", "U11 Life", "U12+", "U19e", "U20 5G"],
    "Desire Series": [
      "Desire 10 Pro",
      "Desire 12",
      "Desire 12+",
      "Desire 19+",
      "Desire 20 Pro",
      "Desire 21 Pro 5G",
      "Desire 22 Pro",
    ],
    "One Series": ["One A9", "One A9s", "One X9", "One X10", "One M9", "One M10"],
    "Wildfire Series": ["Wildfire E", "Wildfire E1", "Wildfire E2", "Wildfire E3"],
  },
  NOKIA: {
    "Nokia 1 Series": ["Nokia 1", "Nokia 1.3", "Nokia 1.4"],
    "Nokia 2 Series": ["Nokia 2", "Nokia 2.1", "Nokia 2.2", "Nokia 2.3", "Nokia 2.4"],
    "Nokia 3 Series": ["Nokia 3", "Nokia 3.1", "Nokia 3.2", "Nokia 3.4"],
    "Nokia 4 Series": ["Nokia 4.2"],
    "Nokia 5 Series": ["Nokia 5", "Nokia 5.1", "Nokia 5.3", "Nokia 5.4"],
    "Nokia 6 Series": ["Nokia 6", "Nokia 6.1", "Nokia 6.2"],
    "Nokia 7 Series": ["Nokia 7", "Nokia 7.1", "Nokia 7.2", "Nokia 7 Plus"],
    "Nokia 8 Series": ["Nokia 8", "Nokia 8.1", "Nokia 8.3 5G", "Nokia 8 Sirocco"],
    "Nokia 9 Series": ["Nokia 9 PureView"],
    "Nokia C Series": [
      "Nokia C1",
      "Nokia C2",
      "Nokia C3",
      "Nokia C5 Endi",
      "Nokia C10",
      "Nokia C20",
      "Nokia C21",
      "Nokia C30",
    ],
    "Nokia G Series": ["Nokia G10", "Nokia G11", "Nokia G20", "Nokia G21", "Nokia G50", "Nokia G60 5G"],
    "Nokia T Series": ["Nokia T10", "Nokia T20"],
    "Nokia X Series": ["Nokia X6", "Nokia X7", "Nokia X10", "Nokia X20", "Nokia X30"],
  },
  TCL: {
    "TCL 10 Series": [
      "TCL 10 5G",
      "TCL 10L",
      "TCL 10 Plus",
      "TCL 10 Pro",
      "TCL 10 SE",
      "TCL 10 TabMax",
      "TCL 10 TabMid",
    ],
    "TCL 20 Series": [
      "TCL 20 5G",
      "TCL 20L",
      "TCL 20L+",
      "TCL 20 Pro 5G",
      "TCL 20R 5G",
      "TCL 20S",
      "TCL 20SE",
      "TCL 20Y",
    ],
    "TCL 30 Series": [
      "TCL 30",
      "TCL 30+",
      "TCL 30 5G",
      "TCL 30E",
      "TCL 30 SE",
      "TCL 30 V 5G",
      "TCL 30 XE 5G",
      "TCL 30 Z",
    ],
    "TCL 40 Series": ["TCL 40 5G", "TCL 40 NxtPaper", "TCL 40 R 5G", "TCL 40 SE", "TCL 40 XE 5G", "TCL 40 XL"],
    "TCL 50 Series": ["TCL 50 5G", "TCL 50 Pro NxtPaper", "TCL 50 XE NxtPaper", "TCL 50 XL NxtPaper"],
    "TCL C Series": ["TCL C5", "TCL C8", "TCL C825", "TCL C835"],
    "TCL A Series": ["TCL A1", "TCL A1X", "TCL A3", "TCL A3X", "TCL A5"],
  },
  ALCATEL: {
    "1 Series": ["1", "1B", "1C", "1S", "1SE", "1T", "1V", "1X"],
    "3 Series": ["3", "3C", "3L", "3T", "3V", "3X"],
    "5 Series": ["5", "5V"],
    "A Series": ["A1", "A3", "A5", "A7"],
    "U Series": ["U3", "U5"],
    "Idol Series": ["Idol 4", "Idol 4S", "Idol 5", "Idol 5S"],
    "Pop Series": ["Pop 4", "Pop 4+", "Pop 4S"],
  },
  ZTE: {
    "Axon Series": [
      "Axon 7",
      "Axon 7 Mini",
      "Axon 7s",
      "Axon 9 Pro",
      "Axon 10 Pro",
      "Axon 10s Pro",
      "Axon 11",
      "Axon 11 SE",
      "Axon 20 5G",
      "Axon 30",
      "Axon 30 Pro",
      "Axon 30 Ultra",
      "Axon 40 Pro",
      "Axon 40 Ultra",
      "Axon 50 Ultra",
    ],
    "Blade Series": [
      "Blade A3",
      "Blade A5",
      "Blade A7",
      "Blade A31",
      "Blade A51",
      "Blade A52",
      "Blade A53",
      "Blade A71",
      "Blade A72",
      "Blade V8",
      "Blade V9",
      "Blade V10",
      "Blade V2020",
      "Blade V30",
      "Blade V40",
      "Blade V50",
    ],
    "nubia Red Magic": [
      "nubia Red Magic",
      "nubia Red Magic Mars",
      "nubia Red Magic 3",
      "nubia Red Magic 3S",
      "nubia Red Magic 5G",
      "nubia Red Magic 5S",
      "nubia Red Magic 6",
      "nubia Red Magic 6 Pro",
      "nubia Red Magic 6S Pro",
      "nubia Red Magic 7",
      "nubia Red Magic 7 Pro",
      "nubia Red Magic 7S",
      "nubia Red Magic 7S Pro",
      "nubia Red Magic 8 Pro",
      "nubia Red Magic 8 Pro+",
      "nubia Red Magic 8S Pro",
      "nubia Red Magic 8S Pro+",
      "nubia Red Magic 9 Pro",
      "nubia Red Magic 9 Pro+",
      "nubia Red Magic 9S Pro",
      "nubia Red Magic 9S Pro+",
    ],
    "nubia Z Series": [
      "nubia Z17",
      "nubia Z17 Mini",
      "nubia Z17 MiniS",
      "nubia Z17S",
      "nubia Z18",
      "nubia Z18 Mini",
      "nubia Z20",
      "nubia Z30 Pro",
      "nubia Z40 Pro",
      "nubia Z50",
      "nubia Z50 Ultra",
      "nubia Z60 Ultra",
    ],
  },
  MEIZU: {
    "16 Series": ["16", "16 Plus", "16s", "16s Pro", "16T", "16th", "16X"],
    "17 Series": ["17", "17 Pro"],
    "18 Series": ["18", "18 Pro", "18s", "18X"],
    "19 Series": ["19", "19 Pro"],
    "20 Series": ["20", "20 Pro", "20 Infinity"],
    "21 Series": ["21", "21 Pro", "21 Note"],
    "Note Series": ["Note 8", "Note 9"],
    "M Series": ["M6", "M6 Note", "M6s", "M6T", "M8", "M8 Lite", "M8c"],
    "C Series": ["C9", "C9 Pro"],
    "X Series": ["X8"],
  },
  INFINIX: {
    "Note Series": [
      "Note 7",
      "Note 7 Lite",
      "Note 8",
      "Note 8i",
      "Note 10",
      "Note 10 Pro",
      "Note 11",
      "Note 11 Pro",
      "Note 11S",
      "Note 12",
      "Note 12 Pro",
      "Note 12 VIP",
      "Note 30",
      "Note 30 Pro",
      "Note 30 VIP",
      "Note 40",
      "Note 40 Pro",
    ],
    "Hot Series": [
      "Hot 8",
      "Hot 9",
      "Hot 9 Play",
      "Hot 10",
      "Hot 10 Lite",
      "Hot 10 Play",
      "Hot 10S",
      "Hot 10T",
      "Hot 11",
      "Hot 11 Play",
      "Hot 11S",
      "Hot 12",
      "Hot 12 Play",
      "Hot 20",
      "Hot 20i",
      "Hot 20S",
      "Hot 30",
      "Hot 30i",
      "Hot 30 Play",
      "Hot 40",
      "Hot 40i",
      "Hot 40 Pro",
    ],
    "Smart Series": [
      "Smart 4",
      "Smart 4 Plus",
      "Smart 5",
      "Smart 5 Pro",
      "Smart 6",
      "Smart 6 HD",
      "Smart 6 Plus",
      "Smart 7",
      "Smart 7 HD",
      "Smart 8",
      "Smart 8 HD",
      "Smart 8 Pro",
    ],
    "Zero Series": ["Zero 8", "Zero 8i", "Zero 20", "Zero 30", "Zero 30 5G", "Zero X", "Zero X Neo", "Zero X Pro"],
    "S Series": ["S4", "S5", "S5 Lite", "S5 Pro"],
  },
  TECNO: {
    "Phantom Series": ["Phantom 9", "Phantom X", "Phantom V Flip", "Phantom V Fold"],
    "Camon Series": [
      "Camon 15",
      "Camon 15 Premier",
      "Camon 15 Pro",
      "Camon 16",
      "Camon 16 Premier",
      "Camon 16 Pro",
      "Camon 16S",
      "Camon 17",
      "Camon 17P",
      "Camon 17 Pro",
      "Camon 18",
      "Camon 18P",
      "Camon 18 Premier",
      "Camon 18T",
      "Camon 19",
      "Camon 19 Neo",
      "Camon 19 Pro",
      "Camon 20",
      "Camon 20 Premier",
      "Camon 20 Pro",
      "Camon 30",
      "Camon 30 Pro",
    ],
    "Spark Series": [
      "Spark 4",
      "Spark 5",
      "Spark 5 Air",
      "Spark 5 Pro",
      "Spark 6",
      "Spark 6 Air",
      "Spark 6 Go",
      "Spark 7",
      "Spark 7P",
      "Spark 7 Pro",
      "Spark 7T",
      "Spark 8",
      "Spark 8C",
      "Spark 8P",
      "Spark 8 Pro",
      "Spark 8T",
      "Spark 9",
      "Spark 9T",
      "Spark 10",
      "Spark 10 5G",
      "Spark 10C",
      "Spark 10 Pro",
      "Spark 20",
      "Spark 20C",
      "Spark 20 Pro",
    ],
    "Pova Series": [
      "Pova",
      "Pova 2",
      "Pova 3",
      "Pova 4",
      "Pova 4 Pro",
      "Pova 5",
      "Pova 5 Pro",
      "Pova 6",
      "Pova 6 Pro",
      "Pova Neo",
      "Pova Neo 2",
      "Pova Neo 3",
    ],
    "Pop Series": [
      "Pop 1",
      "Pop 1 Pro",
      "Pop 2",
      "Pop 2F",
      "Pop 2 Power",
      "Pop 3",
      "Pop 3 Plus",
      "Pop 4",
      "Pop 4 LTE",
      "Pop 4 Pro",
      "Pop 5",
      "Pop 5C",
      "Pop 5 LTE",
      "Pop 5P",
      "Pop 5S",
      "Pop 6",
      "Pop 6 Go",
      "Pop 6 Pro",
      "Pop 7",
      "Pop 7 Pro",
      "Pop 8",
    ],
  },
  BLACKVIEW: {
    "BV Series": [
      "BV4900",
      "BV5500",
      "BV6300",
      "BV6600",
      "BV6900",
      "BV7100",
      "BV8800",
      "BV9900",
      "BV9900E",
      "BV9900 Pro",
    ],
    "A Series": ["A20", "A30", "A50", "A52", "A55", "A60", "A60 Pro", "A70", "A80", "A80 Pro", "A90", "A95"],
    "Tab Series": ["Tab 6", "Tab 8", "Tab 8E", "Tab 9", "Tab 10", "Tab 11", "Tab 12", "Tab 13", "Tab 15", "Tab 16"],
    "Oscal Series": [
      "Oscal C20",
      "Oscal C50",
      "Oscal C60",
      "Oscal C70",
      "Oscal C80",
      "Oscal Pad 8",
      "Oscal Pad 10",
      "Oscal Pad 12",
      "Oscal Pad 13",
      "Oscal Pad 15",
    ],
  },
  ULEFONE: {
    "Armor Series": [
      "Armor 3",
      "Armor 3T",
      "Armor 3W",
      "Armor 3WT",
      "Armor 5",
      "Armor 6",
      "Armor 6E",
      "Armor 6S",
      "Armor 7",
      "Armor 7E",
      "Armor 8",
      "Armor 8 Pro",
      "Armor 9",
      "Armor 9E",
      "Armor 10",
      "Armor 11",
      "Armor 11T",
      "Armor 12",
      "Armor 13",
      "Armor 14",
      "Armor 15",
      "Armor 16",
      "Armor 17 Pro",
      "Armor 18T",
      "Armor 19T",
      "Armor 20WT",
      "Armor 21",
      "Armor 22",
      "Armor 23 Ultra",
      "Armor 24",
      "Armor 25T Pro",
      "Armor 26 Ultra",
      "Armor 27T Pro",
    ],
    "Note Series": [
      "Note 6",
      "Note 7",
      "Note 8",
      "Note 9P",
      "Note 10",
      "Note 11P",
      "Note 12",
      "Note 13P",
      "Note 14",
      "Note 15",
      "Note 16 Pro",
      "Note 17 Pro",
    ],
    "Power Series": ["Power 2", "Power 3", "Power 3L", "Power 3S", "Power 5", "Power 5S", "Power 6"],
    "S Series": ["S1", "S1 Pro", "S7", "S8", "S8 Pro", "S9", "S10", "S11"],
  },
  DOOGEE: {
    "S Series": [
      "S30",
      "S35",
      "S40",
      "S58 Pro",
      "S59",
      "S59 Pro",
      "S68 Pro",
      "S86",
      "S86 Pro",
      "S88 Plus",
      "S88 Pro",
      "S89",
      "S89 Pro",
      "S95",
      "S95 Pro",
      "S96",
      "S96 Pro",
      "S97 Pro",
      "S98",
      "S98 Pro",
      "S100",
      "S110",
      "S118",
    ],
    "V Series": ["V10", "V20", "V30T", "V31GT", "V Max"],
    "N Series": ["N10", "N20", "N30", "N40", "N50", "N50 Pro", "N50S"],
    "X Series": [
      "X5 Max",
      "X5 Max Pro",
      "X6",
      "X6 Pro",
      "X10",
      "X10S",
      "X20",
      "X20L",
      "X30",
      "X50L",
      "X60L",
      "X70",
      "X90L",
      "X95",
      "X95 Pro",
      "X96",
      "X96 Pro",
      "X97 Pro",
      "X100",
    ],
    "T Series": [
      "T3",
      "T5",
      "T5 Lite",
      "T5S",
      "T6",
      "T6 Pro",
      "T10",
      "T10E",
      "T10 Pro",
      "T10S",
      "T20",
      "T20 mini",
      "T30 Max",
      "T30 Pro",
      "T30S",
    ],
  },
  CUBOT: {
    "X Series": ["X15", "X16", "X17", "X18", "X18 Plus", "X19", "X19S", "X20", "X20 Pro", "X30", "X50", "X60", "X70"],
    "Note Series": ["Note 7", "Note 8", "Note 9", "Note 20", "Note 20 Pro", "Note 21", "Note 30", "Note 40"],
    "P Series": ["P20", "P30", "P40", "P50", "P60", "P80"],
    "Max Series": ["Max 2", "Max 3", "Max 5"],
    "King Kong Series": [
      "King Kong",
      "King Kong 3",
      "King Kong 5",
      "King Kong 5 Pro",
      "King Kong 7",
      "King Kong 8",
      "King Kong 9",
      "King Kong CS",
      "King Kong Mini",
      "King Kong Mini 2",
      "King Kong Mini 3",
      "King Kong Power",
      "King Kong Star",
    ],
    "A Series": ["A1", "A5", "A10", "A15"],
    "Pocket Series": ["Pocket", "Pocket 2", "Pocket 3"],
    "Tab Series": ["Tab 10", "Tab 30", "Tab 40", "Tab 50", "Tab Kingkong"],
  },
  OUKITEL: {
    "WP Series": [
      "WP1",
      "WP2",
      "WP5",
      "WP6",
      "WP7",
      "WP8 Pro",
      "WP9",
      "WP10",
      "WP12",
      "WP15",
      "WP17",
      "WP18",
      "WP19",
      "WP20",
      "WP21",
      "WP22",
      "WP23",
      "WP24",
      "WP26",
      "WP27",
      "WP28E",
      "WP30 Pro",
      "WP32",
      "WP33",
    ],
    "K Series": ["K3", "K4", "K5", "K6", "K7", "K8", "K9", "K10", "K12", "K13 Pro", "K15 Pro"],
    "U Series": ["U7 Plus", "U8", "U11 Plus", "U15 Pro", "U16 Max", "U18", "U19", "U20 Plus", "U22", "U23"],
    "C Series": [
      "C3",
      "C4",
      "C5 Pro",
      "C8",
      "C11 Pro",
      "C15 Pro",
      "C17 Pro",
      "C18 Pro",
      "C19 Pro",
      "C21",
      "C22",
      "C24 Pro",
      "C32 Pro",
      "C36",
      "C38",
      "C46",
      "C50",
    ],
    "Y Series": ["Y1000", "Y4800"],
    "Mix Series": ["Mix 2", "Mix 4"],
    "Big Battery Series": [
      "K6000",
      "K6000 Plus",
      "K6000 Pro",
      "K7000",
      "K8000",
      "K9000",
      "K10000",
      "K10000 Pro",
      "K12000 Pro",
      "K13000 Pro",
      "K15000",
    ],
  },
  AGM: {
    "X Series": ["X1", "X2", "X2 SE", "X3", "X5"],
    "A Series": ["A8", "A8 SE", "A9", "A9 JBL", "A10"],
    "H Series": ["H1", "H2", "H3", "H5", "H5 Pro"],
    "G Series": ["G1", "G1S", "G1 Pro", "G2 Guardian"],
    "M Series": ["M5", "M6", "M7", "M8", "M9"],
    "Glory Series": ["Glory", "Glory Pro", "Glory SE"],
    "Pad Series": ["Pad P1", "Pad P2"],
  },
  CAT: {
    "S Series": ["S30", "S31", "S40", "S41", "S48c", "S50", "S52", "S53", "S60", "S61", "S62", "S62 Pro", "S75", "S76"],
    "B Series": ["B15", "B15Q", "B25", "B26", "B30", "B35"],
  },
  RUGGEAR: {
    "RG Series": [
      "RG129",
      "RG160",
      "RG170",
      "RG180",
      "RG310",
      "RG650",
      "RG655",
      "RG725",
      "RG730",
      "RG740",
      "RG760",
      "RG850",
      "RG860",
      "RG870",
      "RG900",
      "RG930",
    ],
  },
}

// Configuraciones de sensibilidad para cada dispositivo
const sensitivityConfigs = {}

// Función para generar configuraciones aleatorias pero realistas
function generateSensitivityConfig(deviceName, configNumber) {
  // Configuraciones más precisas y calibradas por tipo de dispositivo
  const deviceType = getDeviceType(deviceName)
  const baseConfigs = getConfigsByDeviceType(deviceType)

  const config = baseConfigs[configNumber - 1]
  const hasDPI = Math.random() > 0.4 // Más dispositivos con DPI

  return {
    general: Math.floor(Math.random() * (config.general[1] - config.general[0] + 1)) + config.general[0],
    redDot: Math.floor(Math.random() * (config.redDot[1] - config.redDot[0] + 1)) + config.redDot[0],
    scope2x: Math.floor(Math.random() * (config.scope2x[1] - config.scope2x[0] + 1)) + config.scope2x[0],
    scope4x: Math.floor(Math.random() * (config.scope4x[1] - config.scope4x[0] + 1)) + config.scope4x[0],
    awm: Math.floor(Math.random() * (config.awm[1] - config.awm[0] + 1)) + config.awm[0],
    buttonSize: Math.floor(Math.random() * (config.buttonSize[1] - config.buttonSize[0] + 1)) + config.buttonSize[0],
    dpi: hasDPI ? Math.floor(Math.random() * 600) + 800 : "Sin DPI",
    refreshRate: config.refreshRate[Math.floor(Math.random() * config.refreshRate.length)] + "Hz",
  }
}

function getDeviceType(deviceName) {
  if (
    deviceName.includes("Gaming") ||
    deviceName.includes("ROG") ||
    deviceName.includes("Red Magic") ||
    deviceName.includes("Black Shark") ||
    deviceName.includes("Legion")
  ) {
    return "gaming"
  } else if (deviceName.includes("Pro") || deviceName.includes("Ultra") || deviceName.includes("Max")) {
    return "flagship"
  } else if (
    deviceName.includes("Lite") ||
    deviceName.includes("SE") ||
    deviceName.includes("Go") ||
    deviceName.includes("Play")
  ) {
    return "budget"
  } else {
    return "mid-range"
  }
}

function getConfigsByDeviceType(deviceType) {
  const configs = {
    gaming: [
      {
        general: [120, 140],
        redDot: [75, 95],
        scope2x: [78, 98],
        scope4x: [85, 105],
        awm: [95, 115],
        buttonSize: [42, 52],
        refreshRate: [120, 144],
      },
      {
        general: [125, 145],
        redDot: [80, 100],
        scope2x: [82, 102],
        scope4x: [90, 110],
        awm: [100, 120],
        buttonSize: [44, 54],
        refreshRate: [120, 144],
      },
      {
        general: [130, 150],
        redDot: [85, 105],
        scope2x: [86, 106],
        scope4x: [95, 115],
        awm: [105, 125],
        buttonSize: [46, 56],
        refreshRate: [144, 144],
      },
      {
        general: [135, 155],
        redDot: [90, 110],
        scope2x: [90, 110],
        scope4x: [100, 120],
        awm: [110, 130],
        buttonSize: [48, 58],
        refreshRate: [144, 144],
      },
      {
        general: [140, 160],
        redDot: [95, 115],
        scope2x: [94, 114],
        scope4x: [105, 125],
        awm: [115, 135],
        buttonSize: [50, 60],
        refreshRate: [144, 144],
      },
      {
        general: [145, 165],
        redDot: [100, 120],
        scope2x: [98, 118],
        scope4x: [110, 130],
        awm: [120, 140],
        buttonSize: [52, 62],
        refreshRate: [144, 144],
      },
      {
        general: [150, 170],
        redDot: [105, 125],
        scope2x: [102, 122],
        scope4x: [115, 135],
        awm: [125, 145],
        buttonSize: [54, 64],
        refreshRate: [144, 144],
      },
      {
        general: [155, 175],
        redDot: [110, 130],
        scope2x: [106, 126],
        scope4x: [120, 140],
        awm: [130, 150],
        buttonSize: [56, 66],
        refreshRate: [144, 144],
      },
    ],
    flagship: [
      {
        general: [110, 130],
        redDot: [65, 85],
        scope2x: [68, 88],
        scope4x: [75, 95],
        awm: [85, 105],
        buttonSize: [38, 48],
        refreshRate: [90, 144],
      },
      {
        general: [115, 135],
        redDot: [70, 90],
        scope2x: [72, 92],
        scope4x: [80, 100],
        awm: [90, 110],
        buttonSize: [40, 50],
        refreshRate: [90, 144],
      },
      {
        general: [120, 140],
        redDot: [75, 95],
        scope2x: [76, 96],
        scope4x: [85, 105],
        awm: [95, 115],
        buttonSize: [42, 52],
        refreshRate: [120, 144],
      },
      {
        general: [125, 145],
        redDot: [80, 100],
        scope2x: [80, 100],
        scope4x: [90, 110],
        awm: [100, 120],
        buttonSize: [44, 54],
        refreshRate: [120, 144],
      },
      {
        general: [130, 150],
        redDot: [85, 105],
        scope2x: [84, 104],
        scope4x: [95, 115],
        awm: [105, 125],
        buttonSize: [46, 56],
        refreshRate: [120, 144],
      },
      {
        general: [135, 155],
        redDot: [90, 110],
        scope2x: [88, 108],
        scope4x: [100, 120],
        awm: [110, 130],
        buttonSize: [48, 58],
        refreshRate: [120, 144],
      },
      {
        general: [140, 160],
        redDot: [95, 115],
        scope2x: [92, 112],
        scope4x: [105, 125],
        awm: [115, 135],
        buttonSize: [50, 60],
        refreshRate: [120, 144],
      },
      {
        general: [145, 165],
        redDot: [100, 120],
        scope2x: [96, 116],
        scope4x: [110, 130],
        awm: [120, 140],
        buttonSize: [52, 62],
        refreshRate: [120, 144],
      },
    ],
    "mid-range": [
      {
        general: [100, 120],
        redDot: [55, 75],
        scope2x: [58, 78],
        scope4x: [65, 85],
        awm: [75, 95],
        buttonSize: [34, 44],
        refreshRate: [60, 120],
      },
      {
        general: [105, 125],
        redDot: [60, 80],
        scope2x: [62, 82],
        scope4x: [70, 90],
        awm: [80, 100],
        buttonSize: [36, 46],
        refreshRate: [60, 120],
      },
      {
        general: [110, 130],
        redDot: [65, 85],
        scope2x: [66, 86],
        scope4x: [75, 95],
        awm: [85, 105],
        buttonSize: [38, 48],
        refreshRate: [90, 120],
      },
      {
        general: [115, 135],
        redDot: [70, 90],
        scope2x: [70, 90],
        scope4x: [80, 100],
        awm: [90, 110],
        buttonSize: [40, 50],
        refreshRate: [90, 120],
      },
      {
        general: [120, 140],
        redDot: [75, 95],
        scope2x: [74, 94],
        scope4x: [85, 105],
        awm: [95, 115],
        buttonSize: [42, 52],
        refreshRate: [90, 120],
      },
      {
        general: [125, 145],
        redDot: [80, 100],
        scope2x: [78, 98],
        scope4x: [90, 110],
        awm: [100, 120],
        buttonSize: [44, 54],
        refreshRate: [90, 120],
      },
      {
        general: [130, 150],
        redDot: [85, 105],
        scope2x: [82, 102],
        scope4x: [95, 115],
        awm: [105, 125],
        buttonSize: [46, 56],
        refreshRate: [90, 120],
      },
      {
        general: [135, 155],
        redDot: [90, 110],
        scope2x: [86, 106],
        scope4x: [100, 120],
        awm: [110, 130],
        buttonSize: [48, 58],
        refreshRate: [90, 120],
      },
    ],
    budget: [
      {
        general: [90, 110],
        redDot: [45, 65],
        scope2x: [48, 68],
        scope4x: [55, 75],
        awm: [65, 85],
        buttonSize: [30, 40],
        refreshRate: [60, 90],
      },
      {
        general: [95, 115],
        redDot: [50, 70],
        scope2x: [52, 72],
        scope4x: [60, 80],
        awm: [70, 90],
        buttonSize: [32, 42],
        refreshRate: [60, 90],
      },
      {
        general: [100, 120],
        redDot: [55, 75],
        scope2x: [56, 76],
        scope4x: [65, 85],
        awm: [75, 95],
        buttonSize: [34, 44],
        refreshRate: [60, 90],
      },
      {
        general: [105, 125],
        redDot: [60, 80],
        scope2x: [60, 80],
        scope4x: [70, 90],
        awm: [80, 100],
        buttonSize: [36, 46],
        refreshRate: [60, 90],
      },
      {
        general: [110, 130],
        redDot: [65, 85],
        scope2x: [64, 84],
        scope4x: [75, 95],
        awm: [85, 105],
        buttonSize: [38, 48],
        refreshRate: [60, 90],
      },
      {
        general: [115, 135],
        redDot: [70, 90],
        scope2x: [68, 88],
        scope4x: [80, 100],
        awm: [90, 110],
        buttonSize: [40, 50],
        refreshRate: [60, 90],
      },
      {
        general: [120, 140],
        redDot: [75, 95],
        scope2x: [72, 92],
        scope4x: [85, 105],
        awm: [95, 115],
        buttonSize: [42, 52],
        refreshRate: [60, 90],
      },
      {
        general: [125, 145],
        redDot: [80, 100],
        scope2x: [76, 96],
        scope4x: [90, 110],
        awm: [100, 120],
        buttonSize: [44, 54],
        refreshRate: [60, 90],
      },
    ],
  }

  return configs[deviceType] || configs["mid-range"]
}

// Inicializar configuraciones para todos los dispositivos
function initializeSensitivityConfigs() {
  Object.keys(deviceDatabase).forEach((brand) => {
    Object.keys(deviceDatabase[brand]).forEach((series) => {
      deviceDatabase[brand][series].forEach((model) => {
        const deviceKey = `${brand}_${model}`
        sensitivityConfigs[deviceKey] = []

        for (let i = 1; i <= 8; i++) {
          sensitivityConfigs[deviceKey].push(generateSensitivityConfig(model, i))
        }
      })
    })
  })
}

// Variables globales
let currentDevice = null
let currentConfigs = []
let currentConfigIndex = 0

// Elementos del DOM
const brandSelect = document.getElementById("brand-select")
const modelSelect = document.getElementById("model-select")
const generateBtn = document.getElementById("generate-btn")
const regenerateBtn = document.getElementById("regenerate-btn")
const showAllBtn = document.getElementById("show-all-btn")
const configDisplay = document.getElementById("config-display")
const allConfigsDiv = document.getElementById("all-configs")

// Inicializar la aplicación
function initializeApp() {
  initializeSensitivityConfigs()
  populateBrandSelect()
  setupEventListeners()
}

// Poblar el selector de marcas
function populateBrandSelect() {
  const brands = Object.keys(deviceDatabase).sort()
  brands.forEach((brand) => {
    const option = document.createElement("option")
    option.value = brand
    option.textContent = brand
    brandSelect.appendChild(option)
  })
}

// Poblar el selector de modelos
function populateModelSelect(brand) {
  modelSelect.innerHTML = '<option value="">Selecciona un modelo</option>'

  if (!brand) {
    modelSelect.disabled = true
    generateBtn.disabled = true
    return
  }

  const models = []
  Object.keys(deviceDatabase[brand]).forEach((series) => {
    deviceDatabase[brand][series].forEach((model) => {
      models.push(model)
    })
  })

  models.sort().forEach((model) => {
    const option = document.createElement("option")
    option.value = model
    option.textContent = model
    modelSelect.appendChild(option)
  })

  modelSelect.disabled = false
}

// Configurar event listeners
function setupEventListeners() {
  brandSelect.addEventListener("change", (e) => {
    populateModelSelect(e.target.value)
    hideConfigDisplays()
  })

  modelSelect.addEventListener("change", (e) => {
    if (e.target.value) {
      generateBtn.disabled = false
      currentDevice = `${brandSelect.value}_${e.target.value}`
      currentConfigs = sensitivityConfigs[currentDevice]
    } else {
      generateBtn.disabled = true
      currentDevice = null
    }
    hideConfigDisplays()
  })

  generateBtn.addEventListener("click", generateRandomConfig)
  regenerateBtn.addEventListener("click", generateRandomConfig)
  showAllBtn.addEventListener("click", showAllConfigs)
}

// Generar configuración aleatoria
function generateRandomConfig() {
  if (!currentDevice || !currentConfigs) return

  currentConfigIndex = Math.floor(Math.random() * 8)
  const config = currentConfigs[currentConfigIndex]

  displayConfig(config, currentConfigIndex + 1)
  allConfigsDiv.style.display = "none"
}

// Mostrar configuración
function displayConfig(config, configNumber) {
  document.getElementById("device-name").textContent = modelSelect.value
  document.getElementById("config-number").textContent = `Configuración #${configNumber}`

  document.getElementById("general-value").textContent = config.general
  document.getElementById("red-dot-value").textContent = config.redDot
  document.getElementById("scope-2x-value").textContent = config.scope2x
  document.getElementById("scope-4x-value").textContent = config.scope4x
  document.getElementById("awm-value").textContent = config.awm
  document.getElementById("button-size-value").textContent = config.buttonSize
  document.getElementById("dpi-value").textContent = config.dpi
  document.getElementById("refresh-rate-value").textContent = config.refreshRate

  configDisplay.style.display = "block"
}

// Mostrar todas las configuraciones
function showAllConfigs() {
  if (!currentDevice || !currentConfigs) return

  const configsTable = document.getElementById("configs-table")
  configsTable.innerHTML = ""

  // Crear encabezado
  const headerRow = document.createElement("div")
  headerRow.className = "config-row"
  headerRow.innerHTML = `
        <div>Config</div>
        <div>General</div>
        <div>P. Rojo</div>
        <div>X2</div>
        <div>X4</div>
        <div>AWM</div>
        <div>Botón</div>
        <div>DPI</div>
        <div>Hz</div>
    `
  configsTable.appendChild(headerRow)

  // Crear filas de configuraciones
  currentConfigs.forEach((config, index) => {
    const row = document.createElement("div")
    row.className = "config-row"
    row.innerHTML = `
            <div>#${index + 1}</div>
            <div>${config.general}</div>
            <div>${config.redDot}</div>
            <div>${config.scope2x}</div>
            <div>${config.scope4x}</div>
            <div>${config.awm}</div>
            <div>${config.buttonSize}</div>
            <div>${config.dpi}</div>
            <div>${config.refreshRate}</div>
        `

    row.addEventListener("click", () => {
      displayConfig(config, index + 1)
      allConfigsDiv.style.display = "none"
    })

    configsTable.appendChild(row)
  })

  allConfigsDiv.style.display = "block"
}

// Ocultar displays de configuración
function hideConfigDisplays() {
  configDisplay.style.display = "none"
  allConfigsDiv.style.display = "none"
}

// Inicializar la aplicación cuando se carga la página
document.addEventListener("DOMContentLoaded", initializeApp)
